### ISSUE TITLE
Container-fluid inside container issue

### ISSUE THREAD

**Issue by allforabit** [arshad/compass_radix#12]
http://getbootstrap.com/css/#overview-container It says containers shouldn't be nested here. I see it's difficult to avoid for radix_layouts. The workaround in _layout.scss hardcodes -15px margins to offset the padding. I'm using variables to set the gutter width so this breaks things and throws the layout off. 
Would the ideal solution not be to take containers out of radix_layouts and leave it to the theme to add the necessary containers? Or could the bootstrap variable be factored in instead?

**Comment by arshad** [comment]
In previous versions of Radix, this is how it used to be. No container-wrapping in layouts. 

But we moved it inside a few months ago. See the issue thread here: https://www.drupal.org/node/2334871

Another workaround this is to use a css fix as follows:

```
.container .container {
    width: auto;
}
```
