### ISSUE TITLE
Fontawesome update

### ISSUE THREAD

**Issue by aprioul** [arshad/compass_radix#21]
Please can you update fontawesome, my website is so sensitive and update radix with node.js is not possible.
Actually i have override compass_radix font with [font-awesome-sass](https://github.com/FortAwesome/font-awesome-sass) but i have the fontawesome selector twice (it's not good solution)

Thanks you

**Comment by arshad** [comment]
@aprioul I'll look into this. How did you override the compass_radix fonts?

**Comment by aprioul** [comment]
i just include font-awesome-sass after include compass_radix (it's dirty, i don't like this), for this reason i create this issue.

**Comment by arshad** [comment]
Hi @aprioul, I just published version 3.2.0 with FontAwesome 4.7.0. https://rubygems.org/gems/compass_radix/versions/3.2.0

**Comment by aprioul** [comment]
Nice thanks :+1:
